#pragma once

#include <string>
#include "renderer/RenderingPath.h"

namespace engine
{
	struct AppConfig
	{
		std::string title = "engine";
		int width = 640;
		int height = 480;
		RenderingPath renderingPath = RenderingPath::Forward;
		bool depthTest = true;
		bool cullFace = true;
		std::string defaultScene = "scene_objects";

		// Project root directory for asset loading
		// Preprocessor macro generated by engine/CMakeLists.txt
		std::string assetsDir = PROJECT_ROOT "assets/";
	};
}