#pragma once

#include <string>

namespace engine
{
	struct AppConfig
	{
		std::string title = "engine";
		int width = 640;
		int height = 480;
		bool depthTest = true;
		bool cullFace = true;

		// Project root directory for asset loading
		// Preprocessor macro generated by engine/CMakeLists.txt
		std::string assetsDir = PROJECT_ROOT "assets/";
	};
}