#pragma once

#include <glad/glad.h>
#include "core/Window.h"
#include "core/EventCallbacks.h"
#include "resources/AssetManager.h"
#include "renderer/Renderer.h"

// Forward declarations
namespace engine
{
	class Game;
}

namespace engine
{
	struct AppConfig
	{
		std::string title = "engine";
		int width = 640;
		int height = 480;
		bool depthTest = true;
		bool cullFace = true;

		// Project root directory for asset loading
		// Preprocessor macro generated by engine/CMakeLists.txt
		std::string assetsDir = PROJECT_ROOT "assets/";
	};

	class Application : public EventCallbacks
	{
	public:
		Application(const AppConfig& config);
		~Application();

		void run(std::unique_ptr<Game> game);

		void setClearColor(float r, float g, float b, float a);

		void keyCallback(GLFWwindow* window, int key, int scancode, int action, int mods);
		void mouseButtonCallback(GLFWwindow* window, int button, int action, int mods);
		void resizeCallback(GLFWwindow* window, int width, int height);
		void mouseCallback(GLFWwindow* window, double xPos, double yPos);
		void scrollCallback(GLFWwindow* window, double xOffset, double yOffset);

	private:
		Window _window;
		AssetManager _assets;
		Renderer _renderer;

		int _width, _height;
	};
}